### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by wildlyinaccurate** [wildlyinaccurate/whoopsie#49]
This is a meta issue for tracking v1.0 issues.

- [ ] Add `elements` option that takes screenshots of individual elements instead of the whole page
- [ ] Improve gallery output (#15)
- [ ] Exit with code >0 on failure (#18)
- [ ] Improve error messages (#27)
